Repository salesforce/TransmogrifAI, pull requests merged in 2018-09, with the labels that each got.

#99 Adjust bin values for text features in RFF
  core/src/main/scala/com/salesforce/op/OpWorkflow.scala
  core/src/main/scala/com/salesforce/op/filters/FeatureDistribution.scala
  core/src/main/scala/com/salesforce/op/filters/PreparedFeatures.scala
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilter.scala
  core/src/main/scala/com/salesforce/op/filters/Summary.scala
  core/src/main/scala/com/salesforce/op/filters/package.scala
  core/src/test/scala/com/salesforce/op/filters/FeatureDistributionTest.scala
  core/src/test/scala/com/salesforce/op/filters/PreparedFeaturesTest.scala
  core/src/test/scala/com/salesforce/op/filters/RawFeatureFilterTest.scala
  core/src/test/scala/com/salesforce/op/filters/SummaryTest.scala
Labels: ready for review

#117 Parallelized builds & enabled compile cache
  .circleci/config.yml
  .travis.yml
  build.gradle
  gradle.properties
  gradle/version-properties.gradle
Labels: cla:signed

#118 Build configs cleanups
  .circleci/config.yml
  .travis.yml
  build.gradle
  gradle/version-properties.gradle
Labels: work in progress

#120 Specify categorical variables in metadata
  core/src/test/scala/com/salesforce/op/stages/impl/feature/AttributeAsserts.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/Base64VectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/BinaryMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/BinaryVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DateListVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DateMapToUnitCircleVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DateMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DateTimeVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DateToUnitCircleTransformerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DateVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DecisionTreeNumericBucketizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DecisionTreeNumericMapBucketizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DropIndicesByTransformerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/EmailVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/GeolocationMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/GeolocationVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/IntegralMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/IntegralVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/MultiPickListMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/NumericBucketizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/NumericVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OPCollectionHashingVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OPMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OpSetVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/RealMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/RealVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/SmartTextMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/SmartTextVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TextListNullTransformerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TextMapNullEstimatorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TextMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TextTransmogrifyTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TextVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TransmogrifyTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/URLVectorizerTest.scala
  features/src/main/scala/com/salesforce/op/utils/spark/OpVectorMetadata.scala
Labels: work in progress

#131 Typo: metics -> metrics
  core/src/main/scala/com/salesforce/op/evaluators/OpEvaluatorBase.scala
Labels: ready for review

#119 Adding binaryclassification bin score evaluator
  core/src/main/scala/com/salesforce/op/ModelInsights.scala
  core/src/main/scala/com/salesforce/op/evaluators/Evaluators.scala
  core/src/main/scala/com/salesforce/op/evaluators/OpBinScoreEvaluator.scala
  core/src/main/scala/com/salesforce/op/evaluators/OpEvaluatorBase.scala
  core/src/main/scala/com/salesforce/op/stages/impl/classification/BinaryClassificationModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelectorSummary.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowTest.scala
  core/src/test/scala/com/salesforce/op/evaluators/EvaluatorsTest.scala
  core/src/test/scala/com/salesforce/op/evaluators/OpBinScoreEvaluatorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/selector/ModelSelectorTest.scala
Labels: cla:signed

#133 Cleaning up the OpBinScoreEvaluator class a little bit
  core/src/main/scala/com/salesforce/op/evaluators/Evaluators.scala
  core/src/main/scala/com/salesforce/op/evaluators/OpBinScoreEvaluator.scala
  core/src/test/scala/com/salesforce/op/evaluators/OpBinScoreEvaluatorTest.scala
Labels: ready for review

#130 Apply DateToUnitCircleTransformer logic in raw feature transformations.
  core/src/main/scala/com/salesforce/op/OpWorkflow.scala
  core/src/main/scala/com/salesforce/op/filters/PreparedFeatures.scala
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/DateToUnitCircleTransformer.scala
  core/src/test/scala/com/salesforce/op/filters/PreparedFeaturesTest.scala
Labels: cla:signed, needs testing, ready for review

#111 Release 0.4.0
  CHANGELOG.md
  README.md
  build.gradle
  core/src/main/scala/com/salesforce/op/dsl/RichDateFeature.scala
  core/src/main/scala/com/salesforce/op/dsl/RichMapFeature.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala
  docs/examples/Bootstrap-Your-First-Project.md
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  helloworld/README.md
  helloworld/build.gradle
  helloworld/gradle/scalastyle-config.xml
  helloworld/settings.gradle
  helloworld/src/main/scala/com/salesforce/hw/OpTitanicSimple.scala
  helloworld/src/main/scala/com/salesforce/hw/boston/BostonFeatures.scala
  helloworld/src/main/scala/com/salesforce/hw/boston/BostonHouse.scala
  helloworld/src/main/scala/com/salesforce/hw/boston/BostonKryoRegistrator.scala
  helloworld/src/main/scala/com/salesforce/hw/boston/OpBoston.scala
  helloworld/src/main/scala/com/salesforce/hw/dataprep/ConditionalAggregation.scala
  helloworld/src/main/scala/com/salesforce/hw/dataprep/JoinsAndAggregates.scala
  helloworld/src/main/scala/com/salesforce/hw/iris/IrisFeatures.scala
  helloworld/src/main/scala/com/salesforce/hw/iris/IrisKryoRegistrator.scala
  helloworld/src/main/scala/com/salesforce/hw/iris/OpIris.scala
  helloworld/src/main/scala/com/salesforce/hw/titanic/OpTitanic.scala
  helloworld/src/main/scala/com/salesforce/hw/titanic/OpTitanicMini.scala
  helloworld/src/main/scala/com/salesforce/hw/titanic/TitanicFeatures.scala
  helloworld/src/main/scala/com/salesforce/hw/titanic/TitanicKryoRegistrator.scala
  templates/simple/build.gradle.template
Labels: ready for review

#139 changed README.md template to generate correct shell commands
  templates/simple/README.md
Labels: cla:signed

#135 Added support for DateType and TimestampType primitive spark types
  features/src/main/scala/com/salesforce/op/features/FeatureSparkTypes.scala
  features/src/main/scala/com/salesforce/op/features/types/FeatureTypeSparkConverter.scala
  features/src/test/scala/com/salesforce/op/features/FeatureSparkTypeTest.scala
  features/src/test/scala/com/salesforce/op/features/types/FeatureTypeSparkConverterTest.scala
Labels: cla:signed
