Repository salesforce/TransmogrifAI, pull requests merged in 2019-09, with the labels that each got.

#399 Revert back to Spark 2.3
  README.md
  build.gradle
  cli/build.gradle
  cli/src/main/scala/com/salesforce/op/cli/SchemaSource.scala
  cli/src/test/scala/com/salesforce/op/cli/gen/AvroFieldTest.scala
  core/src/main/scala/com/salesforce/op/stages/impl/classification/OpLinearSVC.scala
  core/src/main/scala/com/salesforce/op/stages/impl/classification/OpXGBoostClassifier.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/OpDecisionTreeRegressor.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/OpGBTRegressor.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/OpLinearRegression.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/OpRandomForestRegressor.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/OpXGBoostRegressor.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/sparkwrappers/specific/OpPredictionModel.scala
  core/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostParams.scala
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpPipelineStageReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/classification/OpClassifierModelTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DecisionTreeNumericMapBucketizerTest.scala
  features/src/main/scala/com/salesforce/op/stages/OpPipelineStageReader.scala
  features/src/main/scala/com/salesforce/op/stages/OpPipelineStageReaderWriter.scala
  features/src/main/scala/com/salesforce/op/utils/spark/RichDataset.scala
  features/src/main/scala/org/apache/spark/ml/SparkDefaultParamsReadWrite.scala
  pom.xml
  readers/src/main/scala/com/salesforce/op/readers/CSVAutoReaders.scala
  readers/src/main/scala/org/apache/spark/sql/execution/datasources/csv/CSVSchemaUtils.scala
  templates/simple/build.gradle.template
  utils/build.gradle
  utils/src/main/scala/com/salesforce/op/utils/io/csv/CSVToAvro.scala
  utils/src/main/scala/com/salesforce/op/utils/json/SpecialDoubleSerializer.scala
  utils/src/test/scala/com/salesforce/op/utils/json/SpecialDoubleSerializerTest.scala
Labels: ready for review

#404 Ensure correct metrics despite model failures on some CV folds
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/OpCrossValidation.scala
  core/src/test/scala/com/salesforce/op/stages/impl/regression/RegressionModelSelectorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/selector/ModelSelectorTest.scala
Labels: cla:signed

#403 0.6.1 release
  CHANGELOG.md
  README.md
  docs/examples/Bootstrap-Your-First-Project.md
  docs/examples/Running-from-Spark-Shell.md
  gradle.properties
  helloworld/notebooks/OpHousingPrices.ipynb
  helloworld/notebooks/OpIris.ipynb
  helloworld/notebooks/OpTitanicSimple.ipynb
  local/README.md
  pom.xml
Labels: cla:signed, ready for review, release
