Repository salesforce/TransmogrifAI, pull requests merged in 2019-02, with the labels that each got.

#213 Fix sorting in Prediction type for multiclass classification and add stronger tests
  core/src/test/scala/com/salesforce/op/evaluators/OpMultiClassificationEvaluatorTest.scala
  features/src/main/scala/com/salesforce/op/features/types/Maps.scala
  features/src/test/scala/com/salesforce/op/features/types/FeatureTypeValueTest.scala
  features/src/test/scala/com/salesforce/op/features/types/PredictionTest.scala
Labels: bug, ready for review

#216 Fix indices in LOCO for record-level insights and add more robust tests
  core/src/main/scala/com/salesforce/op/stages/impl/insights/RecordInsightsLOCO.scala
  core/src/test/scala/com/salesforce/op/stages/impl/insights/RecordInsightsLOCOTest.scala
Labels: bug, ready for review

#218 Upgrade to Gradle 5.2
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  helloworld/build.gradle
  helloworld/gradle/wrapper/gradle-wrapper.properties
  helloworld/gradlew
  settings.gradle
  templates/simple/build.gradle.template
  templates/simple/gradle/wrapper/gradle-wrapper.properties
  templates/simple/gradlew
Labels: ready for review

#220 Upgrade shadowjar plugin to 4.0.4 + make license check happy
  build.gradle
  cli/build.gradle
  core/src/main/scala/com/salesforce/op/evaluators/OpBinScoreEvaluator.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/DateMapToUnitCircleVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelectorFactory.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OpStringIndexerTest.scala
  helloworld/build.gradle
  helloworld/gradlew.bat
  templates/simple/build.gradle.template
  templates/simple/gradlew.bat
Labels: ready for review

#221 Make tests a little less flaky
  core/src/test/scala/com/salesforce/op/evaluators/OpMultiClassificationEvaluatorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/insights/RecordInsightsLOCOTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/regression/RegressionModelSelectorTest.scala
Labels: ready for review

#223 Scaler and descaler transformers
  core/src/main/scala/com/salesforce/op/dsl/RichMapFeature.scala
  core/src/main/scala/com/salesforce/op/dsl/RichNumericFeature.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/DescalerTransformer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/ScalerTransformer.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DescalerTransformerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/LinearScalerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/PredictionDescalerTransformerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/ScalerMetadataTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/ScalerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/ScalerTransformerTest.scala
  features/src/main/scala/com/salesforce/op/stages/OpPipelineStageReadWriteShared.scala
  features/src/main/scala/com/salesforce/op/stages/impl/feature/ScalingType.scala
Labels: enhancement, ready for review

#225 Make decision tree numeric bucketizer tests less flaky
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DecisionTreeNumericBucketizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DecisionTreeNumericMapBucketizerTest.scala
Labels: ready for review

#229 Fix rawPrediction of OpXGBoostClassifcationModel for binary classification
  core/src/main/scala/com/salesforce/op/stages/impl/classification/OpXGBoostClassifier.scala
  core/src/test/scala/com/salesforce/op/stages/impl/classification/OpClassifierModelTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/classification/OpXGBoostClassifierTest.scala
Labels: ready for review

#232 Expose some missing Transmogrifier defaults
  core/src/main/scala/com/salesforce/op/stages/impl/feature/Transmogrifier.scala
Labels: ready for review
