Repository salesforce/TransmogrifAI, pull requests merged in 2019-03, with the labels that each got.

#244 Replace 'Spark' with 'Apache Spark' in docs
  docs/faq/index.md
  docs/index.rst
Labels: ready for review

#242 Moved Jupyter guide to docs
  docs/examples/Running-from-Jupyter-Notebook.md
  docs/examples/index.rst
  helloworld/notebooks/README.md
  resources/docker_memory_settings.png
  resources/helloworld_notebooks.png
  resources/notebook_home.png
  resources/op_iris.png
  resources/op_titanic.png
Labels: ready for review

#247 Added blog and video to README
  README.md
Labels: cla:signed

#243 fix local scoring with multipicklist features
  features/src/main/scala/com/salesforce/op/features/types/FeatureTypeSparkConverter.scala
  features/src/test/scala/com/salesforce/op/features/types/FeatureTypeSparkConverterTest.scala
Labels: ready for review

#238 Random param builder for random hyperparameter search in model selectors
  core/src/main/scala/com/salesforce/op/stages/impl/selector/RandomParamBuilder.scala
  core/src/test/scala/com/salesforce/op/stages/impl/selector/RandomParamBuilderTest.scala
Labels: ready for review

#249 MLeap for local model scoring
  build.gradle
  local/README.md
  local/build.gradle
  local/src/main/scala/com/salesforce/op/local/OpWorkflowModelLocal.scala
  local/src/test/scala/com/salesforce/op/local/OpWorkflowRunnerLocalTest.scala
Labels: ready for review

#237 Outputting Raw Feature Filter information: Part 1
  core/src/main/scala/com/salesforce/op/ModelInsights.scala
  core/src/main/scala/com/salesforce/op/OpWorkflow.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowCore.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModel.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelReader.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelWriter.scala
  core/src/main/scala/com/salesforce/op/filters/FeatureDistribution.scala
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilter.scala
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilterResults.scala
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowModelReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/filters/FeatureDistributionTest.scala
  core/src/test/scala/com/salesforce/op/filters/FiltersTestData.scala
  core/src/test/scala/com/salesforce/op/filters/RawFeatureFilterResultsComparison.scala
  core/src/test/scala/com/salesforce/op/filters/RawFeatureFilterTest.scala
Labels: cla:signed, ready for review

#252 Correctly handle error scenario and propagate error message up
  core/src/main/scala/com/salesforce/op/OpWorkflowModelReader.scala
Labels: ready for review

#251 Fix so not preparing data twice when calling model selector fit method
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataBalancer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataSplitter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/OpValidator.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala
  core/src/test/scala/com/salesforce/op/stages/impl/tuning/DataBalancerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/tuning/DataCutterTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/tuning/DataSplitterTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/tuning/OpValidatorTest.scala
Labels: ready for review

#241 Pivot with max cardinality percentage
  core/src/main/scala/com/salesforce/op/dsl/RichLocationFeature.scala
  core/src/main/scala/com/salesforce/op/dsl/RichMapFeature.scala
  core/src/main/scala/com/salesforce/op/dsl/RichSetFeature.scala
  core/src/main/scala/com/salesforce/op/dsl/RichTextFeature.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/MultiPickListMapVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/OpOneHotVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/SmartTextVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/TextMapPivotVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/Transmogrifier.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/EmailVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/MultiPickListMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OpSetVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TextMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TextTransmogrifyTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/UniqueCountTest.scala
  utils/src/main/scala/com/salesforce/op/utils/spark/SequenceAggregators.scala
Labels: cla:signed, ready for review
