Repository salesforce/TransmogrifAI, pull requests merged in 2019-07, with the labels that each got.

#353 Enable CicleCI version 2.1
  .circleci/config.yml
Labels: ready for review

#348 Adding `key` ctor field in all RawFeatureFilter results
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilter.scala
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilterResults.scala
  core/src/test/scala/com/salesforce/op/filters/RawFeatureFilterResultsComparison.scala
  core/src/test/scala/com/salesforce/op/filters/RawFeatureFilterTest.scala
Labels: cla:signed, ready for review

#352 Allow customizing serialization for feature generator extract functions
  features/src/main/java/com/salesforce/op/stages/ReaderWriter.java
  features/src/main/scala/com/salesforce/op/stages/DefaultOpPipelineStageReaderWriter.scala
  features/src/main/scala/com/salesforce/op/stages/DefaultValueReaderWriter.scala
  features/src/main/scala/com/salesforce/op/stages/FeatureGeneratorStage.scala
  features/src/main/scala/com/salesforce/op/stages/OpPipelineStageReaderWriter.scala
  features/src/test/scala/com/salesforce/op/stages/FeatureGeneratorStageTest.scala
Labels: ready for review

#358 Aggregate spark metrics during run time instead of post processing by default
  utils/src/main/scala/com/salesforce/op/utils/spark/OpSparkListener.scala
  utils/src/test/scala/com/salesforce/op/utils/spark/OpSparkListenerTest.scala
Labels: cla:signed

#363 Replace mapValues with immutable Map where applicable
  core/src/main/scala/com/salesforce/op/evaluators/OpMultiClassificationEvaluator.scala
  core/src/main/scala/com/salesforce/op/filters/PreparedFeatures.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/PhoneNumberParser.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/TimePeriodMapTransformer.scala
  core/src/test/scala/com/salesforce/op/filters/PreparedFeaturesTest.scala
  features/src/main/scala/com/salesforce/op/aggregators/ExtendedMultiset.scala
Labels: bug, ready for review

#357 Convert lambda functions into concrete classes to allow compatibility with Scala 2.11/2.12
  core/src/main/scala/com/salesforce/op/dsl/RichDateFeature.scala
  core/src/main/scala/com/salesforce/op/dsl/RichMapFeature.scala
  core/src/main/scala/com/salesforce/op/dsl/RichTextFeature.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/EmailToPickListMapTransformer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/ScalerTransformer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/ToOccurTransformer.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowModelReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/Lambdas.scala
  core/src/test/scala/com/salesforce/op/stages/OpPipelineStagesTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpTransformerBinaryReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpTransformerBinarySequenceReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpTransformerQuaternaryReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpTransformerReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpTransformerSequenceReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpTransformerTernaryReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DropIndicesByTransformerTest.scala
  features/src/test/scala/com/salesforce/op/stages/base/binary/BinaryTransformerTest.scala
  features/src/test/scala/com/salesforce/op/stages/base/quaternary/QuaternaryTransformerTest.scala
  features/src/test/scala/com/salesforce/op/stages/base/sequence/BinarySequenceTransformerTest.scala
  features/src/test/scala/com/salesforce/op/stages/base/sequence/SequenceTransformerTest.scala
  features/src/test/scala/com/salesforce/op/stages/base/ternary/TernaryTransformerTest.scala
  features/src/test/scala/com/salesforce/op/stages/base/unary/UnaryTransformerTest.scala
  readers/src/main/scala/com/salesforce/op/test/PassengerFeaturesTest.scala
Labels: cla:signed, ready for review

#349 Aggregate LOCOs of DateToUnitCircleTransformer.
  core/src/main/scala/com/salesforce/op/stages/impl/insights/RecordInsightsLOCO.scala
  core/src/test/scala/com/salesforce/op/stages/impl/insights/RecordInsightsLOCOTest.scala
Labels: cla:signed, ready for review

#364 0.6.0 release
  CHANGELOG.md
  gradle.properties
Labels: cla:signed, ready for review, release

#367 Bumping Gradle Properties to 0.6.1-SNAPSHOT
  gradle.properties
Labels: cla:signed

#327 Update to Spark 2.4.3 + XGBoost 0.90 + MLeap 0.14
  README.md
  build.gradle
  cli/build.gradle
  cli/src/main/scala/com/salesforce/op/cli/SchemaSource.scala
  cli/src/test/scala/com/salesforce/op/cli/gen/AvroFieldTest.scala
  core/src/main/scala/com/salesforce/op/stages/impl/classification/OpLinearSVC.scala
  core/src/main/scala/com/salesforce/op/stages/impl/classification/OpXGBoostClassifier.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/OpDecisionTreeRegressor.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/OpGBTRegressor.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/OpLinearRegression.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/OpRandomForestRegressor.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/OpXGBoostRegressor.scala
  core/src/main/scala/com/salesforce/op/stages/sparkwrappers/specific/OpPredictionModel.scala
  core/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostParams.scala
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpPipelineStageReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/classification/OpClassifierModelTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DecisionTreeNumericMapBucketizerTest.scala
  features/src/main/scala/com/salesforce/op/stages/OpPipelineStageReader.scala
  features/src/main/scala/com/salesforce/op/stages/OpPipelineStageReaderWriter.scala
  features/src/main/scala/com/salesforce/op/utils/spark/RichDataset.scala
  features/src/main/scala/org/apache/spark/ml/SparkDefaultParamsReadWrite.scala
  pom.xml
  readers/src/main/scala/com/salesforce/op/readers/CSVAutoReaders.scala
  readers/src/main/scala/org/apache/spark/sql/execution/datasources/csv/CSVSchemaUtils.scala
  templates/simple/build.gradle.template
  utils/build.gradle
  utils/src/main/scala/com/salesforce/op/utils/io/csv/CSVToAvro.scala
  utils/src/main/scala/com/salesforce/op/utils/json/SpecialDoubleSerializer.scala
  utils/src/test/scala/com/salesforce/op/utils/json/SpecialDoubleSerializerTest.scala
Labels: ready for review

#345 Descale feature contribution for Linear Regression & Logistic Regression
  core/src/main/scala/com/salesforce/op/ModelInsights.scala
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
Labels: cla:signed, ready for review

#375 Use compact and compressed model json by default
  core/src/main/scala/com/salesforce/op/OpWorkflowModelWriter.scala
Labels: cla:signed, ready for review
