Repository salesforce/TransmogrifAI, pull requests merged in 2019-01, with the labels that each got.

#202 Correct some syntax/compilation errors in Titanic Binary Classification Docs Example
  docs/examples/Titanic-Binary-Classification.md
Labels: cla:missing

#199 Export model selector defaults + metadata fixes
  core/src/main/scala/com/salesforce/op/evaluators/EvaluationMetrics.scala
  core/src/main/scala/com/salesforce/op/stages/impl/classification/BinaryClassificationModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/TextLenTransformer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/package.scala
  core/src/main/scala/com/salesforce/op/stages/impl/preparators/SanityCheckerMetadata.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/RegressionModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelectorFactory.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelectorSummary.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataBalancer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataSplitter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala
  core/src/test/scala/com/salesforce/op/evaluators/OpRegressionEvaluatorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/classification/BinaryClassificationModelSelectorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelectorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TextMapNullEstimatorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/regression/RegressionModelSelectorTest.scala
  utils/src/main/scala/com/salesforce/op/utils/spark/RichMetadata.scala
  utils/src/test/scala/com/salesforce/op/utils/spark/RichMetadataTest.scala
Labels: ready for review

#195 Adds options for tracking text length in text vectorizers
  core/src/main/scala/com/salesforce/op/dsl/RichMapFeature.scala
  core/src/main/scala/com/salesforce/op/dsl/RichTextFeature.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/OPCollectionHashingVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/SmartTextMapVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/SmartTextVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/Transmogrifier.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/SmartTextMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/SmartTextVectorizerTest.scala
  features/src/main/scala/com/salesforce/op/features/TransientFeature.scala
Labels: ready for review

#204 Use class.getName & update splitter meta parsing
  core/src/main/scala/com/salesforce/op/OpApp.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala
  readers/src/main/scala/com/salesforce/op/readers/JoinedDataReader.scala
  utils/src/main/scala/com/salesforce/op/utils/reflection/ReflectionUtils.scala
Labels: ready for review

#206 Use ParamGridBuilder in model selector grids to allow modifications
  core/src/main/scala/com/salesforce/op/stages/impl/classification/BinaryClassificationModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/RegressionModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelectorFactory.scala
Labels: ready for review

#208 Fixing code generation bug with underscores in names
  cli/passengers_.answers
  cli/src/main/scala/com/salesforce/op/cli/CliExec.scala
  cli/src/main/scala/com/salesforce/op/cli/CommandParser.scala
  cli/src/main/scala/com/salesforce/op/cli/gen/ProblemSchema.scala
  cli/src/test/scala/com/salesforce/op/cli/CliCodeGenerationTest.scala
  cli/src/test/scala/com/salesforce/op/cli/CliTestBase.scala
  gradlew
  test-data/PassengerDataAll_.avsc
Labels: cla:signed
