Repository salesforce/TransmogrifAI, pull requests merged in 2019-08, with the labels that each got.

#372 Making model selectors robust to failing models
  core/src/main/scala/com/salesforce/op/OpWorkflow.scala
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/classification/BinaryClassificationModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/RegressionModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/DefaultSelectorParams.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelectorFactory.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/OpCrossValidation.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/OpTrainValidationSplit.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/OpValidator.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowCVTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/regression/RegressionModelSelectorTest.scala
Labels: ready for review

#354 Track mean & standard deviation of text length as a metric for text feature
  core/src/main/scala/com/salesforce/op/filters/FeatureDistribution.scala
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/SmartTextMapVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/SmartTextVectorizer.scala
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
  core/src/test/scala/com/salesforce/op/filters/FeatureDistributionTest.scala
  core/src/test/scala/com/salesforce/op/filters/FiltersTestData.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/SmartTextMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/SmartTextVectorizerTest.scala
Labels: cla:signed, ready for review

#378 Add metadata to OpStandardScaler to allow for descaling
  core/src/main/scala/com/salesforce/op/stages/impl/feature/OpScalarStandardScaler.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OpScalarStandardScalerTest.scala
Labels: cla:signed, ready for review

#382 Update Apache Tika version to 1.22
  build.gradle
  pom.xml
Labels: cla:signed

#380 Improve json serde error in evalMetFromJson
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelectorSummary.scala
  core/src/test/scala/com/salesforce/op/stages/impl/selector/ModelSelectorSummaryTest.scala
Labels: cla:signed, ready for review

#383 add FeatureDistribution to SerializationFormats
  core/src/main/scala/com/salesforce/op/ModelInsights.scala
Labels: cla:signed

#387 Test to verify that custom metrics appear in model insight metrics
  core/src/main/scala/com/salesforce/op/evaluators/EvaluationMetrics.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelectorSummary.scala
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
Labels: cla:signed, ready for review

#377 Avoid creating SparseVectors for LOCO
  core/src/main/scala/com/salesforce/op/stages/impl/insights/RecordInsightsLOCO.scala
  core/src/test/scala/com/salesforce/op/stages/impl/insights/RecordInsightsLOCOTest.scala
  features/src/main/scala/com/salesforce/op/utils/spark/RichVector.scala
Labels: cla:signed, ready for review

#392 Change code owners
  .github/CODEOWNERS
Labels: ready for review

#395 Fix flaky ModelInsight tests
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
Labels: cla:signed, ready for review
