Repository salesforce/TransmogrifAI, pull requests merged in 2019-04, with the labels that each got.

#259 fix a typing error
  docs/developer-guide/index.md
Labels: cla:signed

#264 Possibility to Return top K positives and top K negatives for LOCO
  core/src/main/scala/com/salesforce/op/stages/impl/insights/RecordInsightsLOCO.scala
  core/src/test/scala/com/salesforce/op/stages/impl/insights/RecordInsightsLOCOTest.scala
Labels: cla:signed, ready for review

#261 Correct conversion of Spark model stages into MLeap local models
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OpStringIndexerTest.scala
  features/src/main/scala/com/salesforce/op/features/types/FeatureTypeSparkConverter.scala
  features/src/test/scala/com/salesforce/op/features/types/FeatureTypeSparkConverterTest.scala
  local/README.md
  local/src/main/scala/com/salesforce/op/local/MLeapModelConverter.scala
  local/src/main/scala/com/salesforce/op/local/OpWorkflowModelLocal.scala
  local/src/main/scala/com/salesforce/op/local/OpWorkflowRunnerLocal.scala
  local/src/test/scala/com/salesforce/op/local/MLeapModelConverterTest.scala
  local/src/test/scala/com/salesforce/op/local/OpWorkflowRunnerLocalTest.scala
Labels: ready for review

#270 Allow copying model instances
  core/src/main/scala/com/salesforce/op/OpWorkflowCore.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModel.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowModelReaderWriterTest.scala
Labels: ready for review

#269 Stub to allow loading models without workflow
  core/src/main/scala/com/salesforce/op/OpWorkflow.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModel.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelReader.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/SubstringTransformer.scala
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowModelReaderWriterTest.scala
Labels: ready for review

#258 Outputting Raw Feature Filter information: Part 2
  core/src/main/scala/com/salesforce/op/ModelInsights.scala
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilter.scala
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilterResults.scala
  core/src/test/resources/OldModelVersion_0_5_1/op-model.json/_SUCCESS
  core/src/test/resources/OldModelVersion_0_5_1/op-model.json/part-00000
  core/src/test/scala/com/salesforce/op/DoubleEquality.scala
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowModelReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/filters/RawFeatureFilterResultsComparison.scala
  core/src/test/scala/com/salesforce/op/filters/RawFeatureFilterTest.scala
Labels: cla:signed, ready for review

#276 Proper UID for Raw Feature Filter
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilter.scala
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilterResults.scala
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
Labels: ready for review

#277 Release 0.5.2
  CHANGELOG.md
  gradle.properties
  helloworld/README.md
Labels: ready for review

#281 Skip serializing estimators + fix test + added empty data transform test
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowModelReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpCalibratorReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpMinMaxEstimatorReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpPipelineStageReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/stages/OpTransformerReaderWriterTest.scala
  features/src/main/scala/com/salesforce/op/stages/OpPipelineStageWriter.scala
  features/src/main/scala/com/salesforce/op/test/OpPipelineStageSpec.scala
  features/src/main/scala/com/salesforce/op/test/OpTransformerSpec.scala
Labels: ready for review

#282 Skip writing empty stages & skip loading stages without uid-s
  core/src/main/scala/com/salesforce/op/OpWorkflowModelReader.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelWriter.scala
Labels: ready for review

#289 Update TextTokenizerTest to use OpTransformerSpec
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TextTokenizerTest.scala
Labels: ready for review

#290 Updated TextMapPivotVectorizerTest to use OpEstimatorSpec
  core/src/main/scala/com/salesforce/op/stages/impl/feature/TextMapPivotVectorizer.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TextMapPivotVectorizerTest.scala
  features/src/main/scala/com/salesforce/op/test/OpEstimatorSpec.scala
Labels: ready for review

#291 Improvements of Vectorizer tests
  core/src/main/scala/com/salesforce/op/stages/impl/feature/OpOneHotVectorizer.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OpSetVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OpTextPivotVectorizerTest.scala
Labels: ready for review

#292 Improved multi pick list map vectorizer test
  core/src/main/scala/com/salesforce/op/stages/impl/feature/MultiPickListMapVectorizer.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/MultiPickListMapVectorizerTest.scala
Labels: ready for review

#295 Added base spec for testing Spark wrapping transformers
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OpIndexToStringTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OpStringIndexerNoFilterTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OpStringIndexerTest.scala
  features/src/main/scala/com/salesforce/op/stages/sparkwrappers/generic/SparkWrapperParams.scala
  features/src/main/scala/com/salesforce/op/test/OpTransformerSpec.scala
  features/src/main/scala/com/salesforce/op/test/SwTransformerSpec.scala
Labels: ready for review

#297 Spec-ifying NGramTest
  core/src/test/scala/com/salesforce/op/stages/impl/feature/NGramTest.scala
Labels: cla:missing

#263 DataCutter-related fixes for multiclass
  core/src/main/scala/com/salesforce/op/stages/impl/feature/OpStringIndexerNoFilter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelectorNames.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataBalancer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataCutter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/DataSplitter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala
  core/src/main/scala/org/apache/spark/ml/attribute/MetadataHelper.scala
  core/src/test/resources/log4j.properties
  core/src/test/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelectorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/VectorsCombinerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/tuning/DataBalancerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/tuning/DataCutterTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/tuning/DataSplitterTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/tuning/OpValidatorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/tuning/SplitterSummaryAsserts.scala
Labels: cla:signed, ready for review

#298 Add random test feature generator to generate datasets with features of *all* types
  features/build.gradle
  features/src/test/scala/com/salesforce/op/features/FeatureBuilderTest.scala
  testkit/src/main/scala/com/salesforce/op/test/FeatureAsserts.scala
  testkit/src/main/scala/com/salesforce/op/test/FeatureTestBase.scala
  testkit/src/main/scala/com/salesforce/op/test/TestFeatureBuilder.scala
  testkit/src/main/scala/com/salesforce/op/testkit/RandomData.scala
  testkit/src/main/scala/com/salesforce/op/testkit/RandomReal.scala
  testkit/src/main/scala/com/salesforce/op/testkit/RandomText.scala
  testkit/src/main/scala/com/salesforce/op/testkit/RandomVector.scala
  testkit/src/test/scala/com/salesforce/op/test/TestFeatureBuilderTest.scala
Labels: ready for review

#293 Threshold metrics calculation fix when unseen labels are present
  core/src/main/scala/com/salesforce/op/evaluators/OpMultiClassificationEvaluator.scala
  core/src/test/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelectorTest.scala
Labels: cla:signed, ready for review
