Repository salesforce/TransmogrifAI, pull requests merged in 2019-05, with the labels that each got.

#304 Workflow test to train a model with features of all feature types
  .gitignore
  core/src/main/scala/com/salesforce/op/stages/impl/tuning/Splitter.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowTest.scala
Labels: ready for review

#306 Bump shadowjar plugin to 5.0.0
  build.gradle
  helloworld/build.gradle
  templates/simple/build.gradle.template
Labels: ready for review

#310 Added util methods to create class/object by name + retrieve type tag by type name
  features/src/main/scala/com/salesforce/op/stages/OpPipelineStageReader.scala
  utils/src/main/scala/com/salesforce/op/utils/reflection/ReflectionUtils.scala
  utils/src/test/scala/com/salesforce/op/utils/reflection/ReflectionUtilsTest.scala
Labels: ready for review

#311 Remove free function aggregation with feature builders
  features/src/main/scala/com/salesforce/op/aggregators/CustomMonoidAggregator.scala
  features/src/main/scala/com/salesforce/op/features/FeatureBuilder.scala
  features/src/test/scala/com/salesforce/op/aggregators/MonoidAggregatorDefaultsTest.scala
  features/src/test/scala/com/salesforce/op/features/FeatureBuilderTest.scala
  readers/src/main/scala/com/salesforce/op/test/PassengerFeaturesTest.scala
  readers/src/test/scala/com/salesforce/op/readers/DataReadersTest.scala
  readers/src/test/scala/com/salesforce/op/readers/JoinedDataReaderDataGenerationTest.scala
Labels: ready for review

#312 Avoid singleton random generators
  testkit/src/main/scala/com/salesforce/op/testkit/ProbabilityOfEmpty.scala
  testkit/src/main/scala/com/salesforce/op/testkit/RandomText.scala
  testkit/src/test/scala/com/salesforce/op/testkit/RandomTextTest.scala
Labels: ready for review

#309 Feature generator stages serialization
  core/src/test/scala/com/salesforce/op/OpWorkflowModelReaderWriterTest.scala
  features/src/main/scala/com/salesforce/op/features/FeatureBuilder.scala
  features/src/main/scala/com/salesforce/op/stages/DefaultOpPipelineStageJsonReaderWriter.scala
  features/src/main/scala/com/salesforce/op/stages/FeatureGeneratorStage.scala
  features/src/main/scala/com/salesforce/op/stages/OpPipelineStageJsonReaderWriter.scala
  features/src/main/scala/com/salesforce/op/stages/OpPipelineStageReadWriteShared.scala
  features/src/test/scala/com/salesforce/op/stages/FeatureGeneratorStageTest.scala
  readers/src/main/scala/com/salesforce/op/readers/JoinedDataReader.scala
  readers/src/main/scala/com/salesforce/op/readers/Reader.scala
  readers/src/main/scala/com/salesforce/op/test/PassengerFeaturesTest.scala
  readers/src/test/scala/com/salesforce/op/readers/DataReadersTest.scala
  testkit/src/main/scala/com/salesforce/op/test/FeatureAsserts.scala
  utils/src/test/scala/com/salesforce/op/utils/reflection/ReflectionUtilsTest.scala
Labels: ready for review

#320 Serialize blacklisted map keys with the model + updated access on workflow/model members
  core/src/main/scala/com/salesforce/op/OpWorkflow.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowCore.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModel.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelReader.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelWriter.scala
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowModelReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DateMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DecisionTreeNumericMapBucketizerTest.scala
  features/src/main/scala/com/salesforce/op/stages/impl/feature/TimePeriod.scala
  local/src/main/scala/com/salesforce/op/local/OpWorkflowModelLocal.scala
  local/src/test/scala/com/salesforce/op/local/OpWorkflowRunnerLocalTest.scala
Labels: ready for review

#321 Correctly pass main class for CLI sub project
  build.gradle
  cli/build.gradle
  helloworld/build.gradle
  templates/simple/build.gradle.template
Labels: ready for review

#323 Improve WeekOfMonth in date transformers
  core/src/main/scala/com/salesforce/op/stages/impl/feature/DateToUnitCircleTransformer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/TimePeriodListTransformer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/TimePeriodMapTransformer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/TimePeriodTransformer.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/DateToUnitCircleTransformerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TimePeriodTransformerTest.scala
  features/src/main/scala/com/salesforce/op/stages/impl/feature/TimePeriod.scala
Labels: cla:signed, ready for review

#325 Add FeatureBuilder.fromSchema
  features/src/main/scala/com/salesforce/op/features/FeatureBuilder.scala
Labels: cla:signed

#326 Added community projects docs section
  docs/examples/Community-Projects.md
  docs/examples/index.rst
Labels: ready for review
