Repository salesforce/TransmogrifAI, pull requests merged in 2020-07, with the labels that each got.

#486 Simplified selectExistingPaths
  utils/src/main/scala/com/salesforce/op/utils/io/avro/AvroInOut.scala
  utils/src/test/scala/com/salesforce/op/utils/io/avro/AvroInOutTest.scala
Labels: cla:signed

#490 Let user specify feature importance type for XGBoost
  core/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoostParams.scala
Labels: cla:signed, ready for review

#489 Train a XGBoost model and use it to score to test MLeap compatability
  core/src/main/scala/com/salesforce/op/stages/impl/classification/BinaryClassificationModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/DefaultSelectorParams.scala
  local/src/test/scala/com/salesforce/op/local/OpWorkflowModelLocalTest.scala
Labels: cla:signed, ready for review

#491 Rename whitelist/blacklist to allowlist/blocklist
  CHANGELOG.md
  core/src/main/scala/com/salesforce/op/ModelInsights.scala
  core/src/main/scala/com/salesforce/op/OpWorkflow.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowCore.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModel.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelReader.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelWriter.scala
  core/src/main/scala/com/salesforce/op/dsl/RichMapFeature.scala
  core/src/main/scala/com/salesforce/op/filters/RawFeatureFilter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/FilterMap.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/Transmogrifier.scala
  core/src/test/resources/OldModelVersion/op-model.json/part-00000
  core/src/test/resources/OldModelVersion_0_5_1/op-model.json/part-00000
  core/src/test/resources/OldModelVersion_0_7_1/op-model.json/_SUCCESS
  core/src/test/resources/OldModelVersion_0_7_1/op-model.json/part-00000
  core/src/test/scala/com/salesforce/op/ModelInsightsTest.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowModelReaderWriterTest.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowTest.scala
  core/src/test/scala/com/salesforce/op/filters/RawFeatureFilterTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/EmailVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/FilterIntegralMapTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/FilterMultiPickListMapTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/FilterTextMapTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/GeolocationMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/IntegralMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/MultiPickListMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/RealMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/TextMapPivotVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/URLVectorizerTest.scala
  docs/developer-guide/index.md
  helloworld/src/main/resources/BostonDataset/housing.names
Labels: ready for review

#494 Fix OpWorkflowModelLocalTest due to flaky XGBoost training
  local/src/test/scala/com/salesforce/op/local/OpWorkflowModelLocalTest.scala
Labels: cla:signed

#497 Avoid hardcoded default evaluators in ModelSelectors
  core/src/main/scala/com/salesforce/op/stages/impl/classification/BinaryClassificationModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/RegressionModelSelector.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelectorFactory.scala
  core/src/test/scala/com/salesforce/op/stages/impl/classification/BinaryClassificationModelSelectorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/classification/MultiClassificationModelSelectorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/regression/RegressionModelSelectorTest.scala
Labels: cla:signed, enhancement, ready for review

#500 Update docs to refer to Spark 2.4
  docs/installation/index.md
Labels: cla:signed

#496 Add signed percentage error histogram to regression evaluator
  core/src/main/scala/com/salesforce/op/evaluators/EvaluationMetrics.scala
  core/src/main/scala/com/salesforce/op/evaluators/OpRegressionEvaluator.scala
  core/src/test/scala/com/salesforce/op/evaluators/OpBinaryClassificationEvaluatorTest.scala
  core/src/test/scala/com/salesforce/op/evaluators/OpRegressionEvaluatorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/selector/ModelSelectorSummaryTest.scala
Labels: cla:signed, enhancement, ready for review

#492 Add thresholded confusion matrix elements to binary classification metrics
  core/src/main/scala/com/salesforce/op/ModelInsights.scala
  core/src/main/scala/com/salesforce/op/evaluators/OpBinaryClassificationEvaluator.scala
  core/src/main/scala/com/salesforce/op/evaluators/OpMultiClassificationEvaluator.scala
  core/src/main/scala/org/apache/spark/mllib/evaluation/RichBinaryClassificationMetrics.scala
  core/src/test/scala/com/salesforce/op/evaluators/OpBinaryClassificationEvaluatorTest.scala
  core/src/test/scala/com/salesforce/op/evaluators/OpMultiClassificationEvaluatorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/selector/ModelSelectorSummaryTest.scala
Labels: cla:signed
