Repository salesforce/TransmogrifAI, pull requests merged in 2020-10, with the labels that each got.

#515 Add topk metrics for multiclass classifier
  core/src/main/scala/com/salesforce/op/evaluators/OpMultiClassificationEvaluator.scala
  core/src/test/scala/com/salesforce/op/evaluators/OpMultiClassificationEvaluatorTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/selector/ModelSelectorSummaryTest.scala
Labels: cla:signed

#508 Incorporate name detection into SmartTextVectorizer
  core/src/main/scala/com/salesforce/op/dsl/RichTextFeature.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/OPCollectionHashingVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/SmartTextMapVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/SmartTextVectorizer.scala
  core/src/main/scala/com/salesforce/op/utils/stages/NameDetectUtils.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/SmartTextMapVectorizerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/SmartTextVectorizerTest.scala
  utils/src/main/scala/com/salesforce/op/test/TestCommon.scala
Labels: enhancement, ready for review

#516 Save model locally and convert to zip before moving to final path and do the reverse for loading
  core/build.gradle
  core/src/main/scala/com/salesforce/op/ModelInsights.scala
  core/src/main/scala/com/salesforce/op/OpWorkflow.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModel.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelReader.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelWriter.scala
  core/src/main/scala/com/salesforce/op/evaluators/OpMultiClassificationEvaluator.scala
  core/src/main/scala/com/salesforce/op/stages/impl/regression/OpGeneralizedLinearRegression.scala
  core/src/test/scala/com/salesforce/op/OpWorkflowRunnerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/regression/OpRandomForestRegressorTest.scala
  features/src/main/scala/com/salesforce/op/stages/SparkStageParam.scala
  local/src/test/scala/com/salesforce/op/local/OpWorkflowModelLocalTest.scala
Labels: ready for review
