Repository salesforce/TransmogrifAI, pull requests merged in 2020-03, with the labels that each got.

#463 Standalone minimum variance estimator
  core/src/main/scala/com/salesforce/op/dsl/RichVectorFeature.scala
  core/src/main/scala/com/salesforce/op/stages/impl/preparators/DerivedFeatureFilterUtils.scala
  core/src/main/scala/com/salesforce/op/stages/impl/preparators/MinVarianceFilter.scala
  core/src/main/scala/com/salesforce/op/stages/impl/preparators/MinVarianceFilterMetadata.scala
  core/src/main/scala/com/salesforce/op/stages/impl/preparators/SanityChecker.scala
  core/src/main/scala/com/salesforce/op/stages/impl/preparators/SanityCheckerMetadata.scala
  core/src/test/scala/com/salesforce/op/stages/impl/preparators/MinVarianceFilterMetadataTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/preparators/MinVarianceFilterTest.scala
Labels: cla:signed, ready for review

#467 Use Spark job grouping to distinguish steps of the machine learning flow
  core/src/main/scala/com/salesforce/op/OpWorkflow.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowCore.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModel.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/ModelSelector.scala
  core/src/main/scala/com/salesforce/op/utils/spark/JobGroupUtil.scala
  core/src/test/scala/com/salesforce/op/utils/spark/JobGroupUtilTest.scala
  utils/src/main/scala/com/salesforce/op/utils/spark/OpSparkListener.scala
  utils/src/main/scala/com/salesforce/op/utils/spark/OpStep.scala
  utils/src/test/scala/com/salesforce/op/utils/spark/OpSparkListenerTest.scala
Labels: enhancement, ready for review

#468 Avoid having to have an implicit SparkSession in OpWorkFlow(Model)
  core/src/main/scala/com/salesforce/op/OpWorkflow.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModel.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelReader.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelWriter.scala
Labels: ready for review

#470 Revert jobgroups OpWorkflowModel.save changes
  core/src/main/scala/com/salesforce/op/OpWorkflowModel.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelReader.scala
  core/src/main/scala/com/salesforce/op/OpWorkflowModelWriter.scala
  core/src/main/scala/com/salesforce/op/utils/spark/JobGroupUtil.scala
Labels: ready for review
