Repository salesforce/TransmogrifAI, pull requests merged in 2020-06, with the labels that each got.

#481 0.7.0 release
  CHANGELOG.md
  gradle.properties
  helloworld/notebooks/OpHousingPrices.ipynb
  helloworld/notebooks/OpIris.ipynb
  helloworld/notebooks/OpTitanicSimple.ipynb
Labels: cla:signed, release

#485 Fix code styling issues
  .gitignore
  build.gradle
  core/src/main/scala/com/salesforce/op/ModelInsights.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/SmartTextMapVectorizer.scala
  core/src/main/scala/com/salesforce/op/stages/impl/selector/SelectedModelCombiner.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/ScalarDivideTransformerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/ScalarSubtractTransformerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/SubstringTransformerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/ValidEmailTransformerTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/preparators/SanityCheckerMetadataTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/selector/RandomParamBuilderTest.scala
  core/src/test/scala/com/salesforce/op/stages/impl/selector/SelectedModelCombinerTest.scala
  features/src/main/java/com/salesforce/op/stages/ReaderWriter.java
  features/src/main/scala/com/salesforce/op/stages/impl/feature/CombinationStrategy.scala
  features/src/main/scala/com/salesforce/op/stages/impl/feature/GenderDetectStrategy.scala
  features/src/main/scala/com/salesforce/op/stages/impl/feature/TextVectorizationMethod.scala
  features/src/main/scala/com/salesforce/op/stages/impl/feature/TimePeriod.scala
Labels: cla:signed, ready for review

#484 Expose derived feature value in model insights
  core/src/main/scala/com/salesforce/op/ModelInsights.scala
  core/src/main/scala/com/salesforce/op/stages/impl/feature/OPMapVectorizer.scala
  core/src/test/scala/com/salesforce/op/stages/impl/feature/OPMapVectorizerTest.scala
Labels: cla:signed

#487 Replace empty XGBoost feature importance with a vector of zeros
  core/src/main/scala/com/salesforce/op/ModelInsights.scala
Labels: cla:signed
